// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdezkmwvgoikgcxtnfju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkZXprbXd2Z29pa2djeHRuZmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDUxNTAsImV4cCI6MjA3MDQ4MTE1MH0._5BguZPfOuI-RYy1HVxlwdfcm-JuebGDY2_z56Xg-PY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});